name: Scrape

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.7'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Scraper
        run: python main.py 
      #- name: Set env vars
      #  run: |
      #    echo "DATE=$(python -c 'import datetime as dt; print(dt.datetime.now().date())')" >> $GITHUB_ENV
      - name: Push to repository
        run: |
          git config --global user.name "whs2k"
          git config --global user.email ${{secrets.GIT_USER_EMAIL}}
          now=$(date)
          git add -A
          git commit -m "Auto Push on $now"
          git push